baseurl = "/"
languageCode = "en-us"
title = "Intricate Mechanisms"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
publishDir = "../AlexLabram.github.io"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/rstudio/blogdown"
    weight = 3
[[menu.main]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/alexlabram/"
    weight = 4

[params]
    description = "A study of complexity."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    # path to the favicon, under "static"
    favicon = "favicon.ico"

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"

